.git
.github
.idea
.gradle
docs
infra
*.md
.env
.env.*
!.env.example

app-server/build
module-account/build
module-receipt/build
module-report/build
module-place/build
module-core/build
buildSrc/build
