plugins {
    id "chapchap.spring-boot-application-conventions"
}

dependencies {
    implementation project(":module-account")
    implementation project(":module-consumption")
    implementation project(":module-report")
    implementation project(":module-place")
    implementation project(":module-core")

    implementation "jakarta.persistence:jakarta.persistence-api"
    implementation "org.springframework.data:spring-data-jpa"
    implementation("com.querydsl:querydsl-jpa") {
        artifact {
            classifier = "jakarta"
        }
    }
    implementation platform("software.amazon.awssdk:bom:${libs.versions.aws.sdk.get()}")
    implementation "software.amazon.awssdk:s3"

    testImplementation testFixtures(project(":module-core"))

    testImplementation "com.tngtech.archunit:archunit-junit5:${libs.versions.archunit.get()}"
    testImplementation "org.springframework.boot:spring-boot-starter-data-redis"
}
