plugins {
    id "chapchap.spring-boot-application-conventions"
}

dependencies {
    implementation project(":module-account")
    implementation project(":module-receipt")
    implementation project(":module-report")
    implementation project(":module-place")
    implementation project(":module-core")

    testImplementation testFixtures(project(":module-core"))
}
