plugins {
    id "chapchap.spring-boot-application-conventions"
}

dependencies {
    implementation project(":module-account")
    implementation project(":module-receipt")
    implementation project(":module-report")
    implementation project(":module-place")
    implementation project(":module-core")

    implementation "jakarta.persistence:jakarta.persistence-api"
    implementation "org.springframework.data:spring-data-jpa"
    implementation("com.querydsl:querydsl-jpa") {
        artifact {
            classifier = "jakarta"
        }
    }

    testImplementation testFixtures(project(":module-core"))

    testImplementation "com.tngtech.archunit:archunit-junit5:${libs.versions.archunit.get()}"
    testImplementation "org.springframework.boot:spring-boot-starter-data-redis"
}
