spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

chapchap:
  cors:
    allowed-origin-patterns: ${CORS_ALLOWED_ORIGIN_PATTERNS}
  oauth:
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      client-secret: ${KAKAO_CLIENT_SECRET}
      admin-key: ${KAKAO_ADMIN_KEY}
      redirect-uri: ${KAKAO_REDIRECT_URI}
    client:
      web-redirect-uri: ${OAUTH_WEB_REDIRECT_URI}
      app-redirect-uri: ${OAUTH_APP_REDIRECT_URI}
  jwt:
    secret: ${JWT_SECRET}
