spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/chapchap
    username: chapchap
    password: chapchap

  flyway:
    locations: classpath:db/migration,classpath:db/dev-data

  data:
    redis:
      host: localhost
      port: 6379

chapchap:
  cors:
    allowed-origin-patterns:
      - "*"
