plugins {
    id "chapchap.spring-library-conventions"
}

dependencies {
    implementation project(":module-core")

    implementation project(":module-consumption")
    implementation project(":module-place")
    implementation project(":module-account")

    testImplementation testFixtures(project(":module-core"))
}
