plugins {
    id "chapchap.spring-library-conventions"
}

dependencies {
    implementation project(":module-core")
    implementation project(":module-consumption")

    implementation "org.springframework.boot:spring-boot-starter-data-redis"
    implementation "org.springframework.boot:spring-boot-starter-oauth2-resource-server"
    implementation platform("software.amazon.awssdk:bom:${libs.versions.aws.sdk.get()}")
    implementation "software.amazon.awssdk:s3"

    testImplementation testFixtures(project(":module-core"))
}
