plugins {
    id "chapchap.spring-library-conventions"
}

dependencies {
    implementation project(":module-core")

    implementation "org.springframework.boot:spring-boot-starter-data-redis"
    implementation "org.springframework.boot:spring-boot-starter-oauth2-client"

    def jjwtVersion = libs.versions.jjwt.get()
    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    runtimeOnly "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"

    testImplementation testFixtures(project(":module-core"))
}
